name: Terraform Deployment
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - run: terraform init
        working-directory: terraform/
      - run: terraform fmt -check
        working-directory: terraform/
      - run: terraform plan
        working-directory: terraform/
      - run: terraform apply -auto-approve
        if: github.ref == 'refs/heads/main'
        working-directory: terraform/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
